# This is the config to install Kubeflow on an existing k8s cluster.

apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: kubeflow_app
  namespace: tekton-pipelines
spec:
  repos:
  - name: manifests
    root: 
    uri: https://github.com/kubeflow/manifests/archive/pull/285/head.tar.gz
  - name: kubeflow
    root: kubeflow-master
    uri: https://github.com/kubeflow/kubeflow/archive/master.tar.gz
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/application-crds
    name: application-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: application/application
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: tektoncd/tektoncd-crds
    name: tektoncd-crds
  - kustomizeConfig:
      parameters:
      - name: project
        value: constant-cubist-173123
      - name: registry
        value: gcr.io/tekton-releases
      repoRef:
        name: manifests
        path: tektoncd/tektoncd-install
    name: tektoncd-install
  - kustomizeConfig:
      overlays:
      - application
      - e2e
      repoRef:
        name: manifests
        path: tektoncd/tektoncd-tasks
    name: tektoncd-tasks
  - kustomizeConfig:
      parameters:
      - name: project
        value: constant-cubist-173123
      - name: email
        value: kam.d.kasravi@intel.com
      - name: pullrequest
        value: refs/pull/10/head
      - name: configPath
        value: https://raw.githubusercontent.com/kkasravi/kfctl/tektoncd_pipelines/config/kfctl_e2e.yaml
      repoRef:
        name: manifests
        path: tektoncd/tektoncd-pipelines
        name: manifests
        path: tektoncd/tektoncd-pipelines
    name: tektoncd-pipelines
  enableApplications: true
  packageManager: kustomize
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
