# This is the config to install Kubeflow on an existing k8s cluster.

apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: kubeflow_app
  namespace: tekton-pipelines
spec:
  repos:
  - name: manifests
    root: 
    uri: https://github.com/kubeflow/manifests/archive/pull/285/head.tar.gz
  - name: kubeflow
    root: kubeflow-master
    uri: https://github.com/kubeflow/kubeflow/archive/master.tar.gz
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: e2e/e2e-pipelineruns
    name: e2e-pipelineruns
  enableApplications: true
  packageManager: kustomize
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
