# This is the config to install Kubeflow on an existing k8s cluster.

apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: kubeflow_app
  namespace: tekton-pipelines
spec:
  repos:
  - name: manifests
    root: 
    uri: https://github.com/kubeflow/manifests/archive/pull/285/head.tar.gz
  - name: kubeflow
    root: kubeflow-master
    uri: https://github.com/kubeflow/kubeflow/archive/master.tar.gz
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/application-crds
    name: application-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: application/application
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: tektoncd/tektoncd-crds
    name: tektoncd-crds
  - kustomizeConfig:
      parameters:
      - name: project
        value: constant-cubist-173123
      - name: registry
        value: gcr.io/tekton-releases
      repoRef:
        name: manifests
        path: tektoncd/tektoncd-install
    name: tektoncd-install
  - kustomizeConfig:
      overlays:
      - application
      - e2e
      repoRef:
        name: manifests
        path: tektoncd/tektoncd-tasks
    name: tektoncd-tasks
  - kustomizeConfig:
      overlays:
      - e2e
      parameters:
      - name: project
        value: constant-cubist-173123
      - name: pullrequest
        value: refs/pull/10/head
      - name: configPath
        value: https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_gcp_iap.yaml
      - name: zone
        value: us-west1-a
      - name: email
        value: docker@constant-cubist-173123.iam.gserviceaccount.com
      - name: platform
        value: all
      - name: image
        value: "gcr.io/kubeflow-ci/test-worker:latest"
      - name: cluster
        value: "kubeflow-testing"
      - name: bucket
        value: kubernetes-jenkins
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: kfctl
      - name: repos_dir
        value: /src
      repoRef:
        name: manifests
        path: tektoncd/tektoncd-pipelines
    name: tektoncd-pipelines
  enableApplications: true
  packageManager: kustomize
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
